### ISSUE TITLE
Methods Which Override Return Types Are Treated Differently By Different JDKs

### ISSUE THREAD

**Issue by ilooner** [siom79/japicmp#86] opened 2015-11-04 17:53 UTC
If a method overrides the return type of a super class method or interface then some jdks produce a non_synthetic, non_bridge method, while others produce a synthetic bridge method. Also some obfuscators produce these differences as well. Since the japicmp plugin is sensitive to this builds can fail when comparing with jars compiled with another jdk, or if the obfuscator treated the previous binaries slightly differently. I would like to add an option to ignore binary differences like the following.

        ***! MODIFIED METHOD: PUBLIC SYNTHETIC (<- NON_SYNTHETIC) BRIDGE (<- NON_BRIDGE) java.lang.Object (<-java.io.Externalizable) read(com.esotericsoftware.kryo.Kryo, com.esotericsoftware.kryo.io.Input, java.lang.Class)

**Comment by siom79** [comment] 2015-11-05 17:02
The reason why the following change was marked as binary incompatible is that the return type of the method has changed from `java.io.Externalizable` to `java.lang.Object`:
```
***! MODIFIED METHOD: PUBLIC SYNTHETIC (<- NON_SYNTHETIC) BRIDGE (<- NON_BRIDGE) java.lang.Object (<-java.io.Externalizable) read(com.esotericsoftware.kryo.Kryo, com.esotericsoftware.kryo.io.Input, java.lang.Class)
```
After compilation the class file contains a reference to the method with the return type `java.io.Externalizable`. Hence when running code against a new version of this library, the JVM will throw a `NoSuchMethodError` similiar to the following one:
```
java.lang.NoSuchMethodError: japicmp.test.Methods.returnValueStringToObject()Ljava/lang/String;
```

**Comment by ilooner** [comment] 2015-11-05 17:48
Thanks @siom79. Then I guess the real issue I'm having is that the compiler is producing bridge and non-bridge methods with different return types inconsistently

The method giving this error
```
PROTECTED NON_SYNTHETIC (<- SYNTHETIC) NON_BRIDGE (<- BRIDGE) com.datatorrent.lib.bucket.Bucket (<-com.datatorrent.lib.bucket.AbstractBucket) createBucket(long)
```
Is defined in a class like this. 
```
  public static class ExternalizableSerializer<T extends Externalizable> extends Serializer<T>
  {
    public T read(Kryo kryo, Input input, Class<T> type)
  }
```
The method signature was not changed since the base jar being compared against was created.

Similarly I am getting the following error
```
PROTECTED NON_SYNTHETIC (<- SYNTHETIC) NON_BRIDGE (<- BRIDGE) xxx.Bucket (<-xxx.AbstractBucket) createBucket(long)
```
for this method
```
protected Bucket<T> createBucket(long bucketKey)
```
This method also was not changed since the base jar was created.

Is there a way to make things consistent?

Thanks

**Comment by siom79** [comment] 2015-11-06 11:09
Are you sure that you haven't changed the type parameter from `T` to `T extends Externalizable`? 

If you haven't changed this, it would mean that some compilers just add `java.lang.Object` as return type for parameterized methods and others the restrictions to `java.io.Externalizable`. But in the next step, this would mean that the compiled class files are really binary incompatible as the old version would run without problems when assigning the return value to a variable of type `java.lang.Object`. Using this code with the new version (compiled with a different compiler), than the code would thrown an exception.

Which compilers did you use?

**Comment by siom79** [comment] 2016-01-02 14:06
Could not reproduce.

**Closed by siom79** 2016-01-02 14:06 UTC
