### ISSUE TITLE
New default method detected as METHOD_NEW_DEFAULT when BinaryIncompatible disabled and SourceIncompatible enabled

### ISSUE THREAD

**Issue by WencongLiu** [siom79/japicmp#361] opened 2023-08-31 04:26 UTC
Hello community,

I added a new default method to a class and only set SourceIncompatible to true. The BinaryIncompatible is set to false. The configuration is below:
`<breakBuildOnBinaryIncompatibleModifications>false</breakBuildOnBinaryIncompatibleModifications>
							<breakBuildOnSourceIncompatibleModifications>true</breakBuildOnSourceIncompatibleModifications>
`

But japicmp plugin detects that there is METHOD_NEW_DEFAULT. The version of japicmp is 0.17.1.1_m325. 

Should adding default method to an interface be detected as METHOD_NEW_DEFAULT when only SourceIncompatible is set to true ?

**Comment by siom79** [comment] 2023-09-02 09:15
Duplicate of #289

**Closed by siom79** 2023-09-02 09:15 UTC
