### ISSUE TITLE
METHOD_NOW_FINAL false positive on `private …` to `protected final …` change

### ISSUE THREAD

**Issue by chrisvest** [siom79/japicmp#295] opened 2021-08-18 13:03 UTC
I had the following method:

```java
    private boolean useIpv6(InetAddress address) {
        …
    }
```

and changed it to

```java
    protected final boolean useIpv6(InetAddress address) {
        …
    }
```

which produced the following complaint from japicmp:

```
There is at least one incompatibility: io.netty.channel.unix.Socket.useIpv6(java.net.InetAddress):METHOD_NOW_FINAL
```

I worked around it by introducing a static method in https://github.com/netty/netty/pull/11588/commits/2b7057562d3d5bf722e910289ad90dd733291ec1 but I think that should not be necessary.

This is with using japicmp maven plug-in version `0.15.3`.

**Comment by normanmaurer** [comment] 2021-10-06 11:55
This might be a duplicate of https://github.com/siom79/japicmp/issues/265

**Closed** 2024-10-08 20:30 UTC
